### ISSUE TITLE
Bugs & Possible Enhancements

### ISSUE THREAD

**Issue by agjs** [ReynotRay/thinkful-career-path#3]
# Startup landing page
#### HTML
- You have a typo on line 31 - should be "section", **not** sesction
- You have a typo on line 32 - should be `<section class="cases">, not <section= class "cases">`
- Instead of setting width and height of the images, you add a class to each image for instance class="img" and in the CSS you add the appropriate values e.g.:
  .img {
  width:127px;
  height:127px;
  }
- In programming we have one very strict and basic rule, **never repeat yourself**
- On line 61 it should be `<ul class="icon">...</ul>, not <ul class-"icon">...</ul>` - but even if you didn't make a typo, there is a better way to do this, try to figure out better way to create an icon instead of creating entire unordered list (hint, try using span instead)
- On line 21 you have `style="width:26"`. 26 of what ? Apples :D ? While incorrect we still don't want to write our CSS inline, so rather if you need this specific element to have custom styling, add an id to it and then write your css in your style.css file.
- We mentioned code formatting last time, yours is not very readable. Until we configure your sublime text, try copy pasting your HTML to http://www.dirtymarkup.com/ then clicking clean and copy / paste it back to your editor. We need to keep our code organised and easy to read. Example of your code when ran through dirtymarkup.com: https://gist.github.com/agjs/b89f1f0dcb400077b0df
#### CSS
- I believe you have some HTML in your CSS file, you might want to delete that :), line 84 - 90
- You should write your CSS corresponding to the element order in your HTML, for instance, the first tag in your HTML is the `<html>` tag itself, followed by `<body>` (lets ignore `<head>` since that's the place where we only declare or link new files, we can't style that). So what you should generally do is, have HTML and body tags first in your CSS file and then order your css by its order in HTML. In this concrete example, first thing in your style.css file should be body, introduction, followed by button, div, li, top-navigation and lastly, cases, devices.
#### Notes
- While we gonna discuss this entire list in our session, make sure to fix everything before we meet tomorrow so we can utilise time better. 
- **Hint** - Make sure to read through all the CSS selectors which might be confusing, I will ask you some questions regarding this. 
- Try to prepare as best as possible and think of me as your boss who expects great results.

**Comment by ReynotRay** [comment]
Hi Aleks,

Thanks for the feedback.

I am currently working on the material and should have it finished by this
evening.

Rey

On Tue, Mar 8, 2016 at 5:12 PM, Aleksandar Grbic notifications@github.com
wrote:

> Assigned #3 https://github.com/ReynotRay/Thinkful-career-path/issues/3
> to @ReynotRay https://github.com/ReynotRay.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ReynotRay/Thinkful-career-path/issues/3#event-582502002
> .

ᐧ

**Comment by agjs** [comment]
- This is how your CSS should look like syntactically correct [CSS Improvements](https://gist.github.com/agjs/809f1a6e8dfe19960e29). I'm not going to talk now about selectors etc. we gonna do that in our session but in order for CSS file to be rendered and read probably, it needs to be correctly written so browser can parse the file.
- You have several errors in your CSS file, one of them is at **line 111** `img .logo { margin-left: }` where you have used `margin-left`without setting the value. If this is unnecessary, just remove it.
- At **line 116** you have unnecessary characters, most probably, broken comment so just remove it.
- At **line 119** and **line 121** you have extra `}`, they are not closing any selectors and you need to remove them
- On **line 67** you have an extra `}`, remove it
- In general, don't leave unnecessary comments in your files. Unless they are real comments and provide explanation to some rather unusual or complex code, leaving unused code commented just creates a clutter and confusion, so just remove it
- Follow some code style guide. When making space between selectors, make sure the space is always the same, usually 1 like as you can see on the CSS example I provided.

#### Notes
- In terms of both, HTML and CSS, we are going to do improvements together, so no worries. If you have time, try to fix the CSS thingies above.

#### CSS Styleguide
- This is the [Style Guide](https://github.com/airbnb/css) I want you to bookmark and use while writing your CSS. Every time you write some CSS, open this file and follow best practices, until you eventually learn it all. 

#### HTML Styleguide
- Same applies to HTML. Bookmark [this styleguide](http://www.w3schools.com/html/html5_syntax.asp) and use it when writing your HTML
